# Generated by Django 5.2.1 on 2025-05-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0002_initial'),
        ('contractor', '0002_initial'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorassignment',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignments', to='contractor.contractor'),
        ),
        migrations.AddField(
            model_name='issue',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='contractor.contractor'),
        ),
        migrations.AddField(
            model_name='issue',
            name='government_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_issues', to='authorities.authority'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorassignment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issueimage',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issueimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueupvote',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issueupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='contractor.contractor'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='issueupvote',
            unique_together={('issue', 'user')},
        ),
    ]
